### ISSUE TITLE
why do you even use the eliptic curve at all?

### ISSUE THREAD

**Issue by kropple** [RealityRipple/php-bitcoin-cashaddr#1]
why do you use the maths at all?
converting a 1... or 3... bitcoin address to a cashaddr is simply decoding the b58 and encoding bech32-cashaddr.
and converting a bc1... address is not really needed or is it?

**Comment by RealityRipple** [comment]
`phpecc` is included specifically to make use of the `/classes/util/bcmath_Utils.php` and `/classes/util/gmp_Utils.php` files. This is done for efficiency sake as it's assumed that anyone using cashaddr may also end up wanting to use the ec components. If you don't like the dependency, just copy the used functions from those two classes to the `bigint.php` file.
